CREATE DATABASE BANKDB;
USE BANKDB;

CREATE TABLE ACCOUNTS(
ACC_ID INT PRIMARY KEY,
ACC_HOLDER VARCHAR(100),
BALANCE DECIMAL(10,2) CHECK (BALANCE>=0)
);

INSERT INTO ACCOUNTS VALUES
(1,'A',5000.00),(2,'B',3000.00);

-- AUTOMICITY 
START TRANSACTION;

UPDATE ACCOUNTS 
SET BALANCE =BALANCE - 1000
WHERE ACC_ID =1;

SELECT * FROM ACCOUNTS;

UPDATE ACCOUNTS 
SET BALANCE =BALANCE + 1000
WHERE ACC_ID =2;

COMMIT;

START TRANSACTION;
UPDATE ACCOUNTS 
SET BALANCE =BALANCE - 1000
WHERE ACC_ID =1;

UPDATE ACCOUNTS 
SET BALANCE =BALANCE - 1000
WHERE ACC_ID =99;

ROLLBACK;
SELECT * FROM ACCOUNTS;
COMMIT;

-- CONSISTANCY
SELECT * FROM ACCOUNTS;

START TRANSACTION;

UPDATE ACCOUNTS 
SET BALANCE =BALANCE - 6000
WHERE ACC_ID =1;


-- ISOLATION 


CREATE TABLE ACCOUNTS1(
ACC_ID INT PRIMARY KEY,
ACC_HOLDER VARCHAR(100),
BALANCE DECIMAL(10,2) CHECK (BALANCE>=0)
);

INSERT INTO ACCOUNTS1 VALUES
(1,'FATHER',1000);


-- PERSON A 
START TRANSACTION ;
SELECT BALANCE FROM ACCOUNTS1 WHERE ACC_ID=1;
UPDATE ACCOUNTS1 
SET BALANCE =BALANCE - 800
WHERE ACC_ID =1;


-- PERSON B
START TRANSACTION ;
SELECT BALANCE FROM ACCOUNTS1 WHERE ACC_ID=1;
UPDATE ACCOUNTS1
SET BALANCE =BALANCE - 800
WHERE ACC_ID =1;
SELECT BALANCE FROM ACCOUNTS1 WHERE ACC_ID=1;



-- TRIGGERS
CREATE DATABASE TRIGGERDB;
USE TRIGGERDB;

CREATE TABLE EMPLOYEE(
EMPID INT PRIMARY KEY ,
NAME VARCHAR(50),
SALARY DECIMAL(10,2),
PENDINGINVOICE DECIMAL(10,2) DEFAULT 0
);

CREATE TABLE EMPLOYE_LOG (
LOGID INT AUTO_INCREMENT PRIMARY KEY ,
EMPID INT ,
ACTIONTYPE VARCHAR(50),
OLDSALARY DECIMAL(10,2),
NEWSALARY DECIMAL(10,2),
LOGTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO EMPLOYEE VALUES 
(1,'RAVI',50000,2000),
(2,'RAJU',30000,0),
(3,'RAM',45000,0);



-- BEFORE INSERT ,AFTER INSERT 
DELIMITER //
CREATE TRIGGER BEFORE_INSERT_EMP
BEFORE INSERT ON EMPLOYEE FOR EACH ROW 
BEGIN 
IF NEW.SALARY<0 THEN 
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT ="SALARY CANNOT BE NAGATIVE";
END IF;
END//
DELIMITER ;


-- AFTER INSERT 
DELIMITER //
CREATE TRIGGER AFTE
AFTER INSERT ON EMPLOYEE FOR EACH ROW 
BEGIN 
INSERT INTO EMPLOYEE_LOG (EMPID,ACTIONTYPE ,NEWSALARY)
VALUES
(NEW.EMPID,'INSERTED',NEW.SALARY);
DELIMITER ;


-- BEFORE UPDATE AFTER UPDATE 
-- SALARY INCREASE CANNOT EXCEEDS 80%

DELIMITER //
CREATE TRIGGER BEFORE_UPDATE_EMP
BEFORE UPDATE ON EMPLOYEE FOR EACH ROW 
BEGIN 
IF NEW.SALARY>OLD.SALARY*1.8 THEN 
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT='SALARY INCREASE CANNOT EXCEED 80%';
END IF;
END//
DELIMITER ;

-- AFTER UPDATE 
DELIMITER //
CREATE TRIGGER AFTER_UPDATE_EMP
AFTER UPDATE ON  EMPLOYEE FOR EACH ROW 
BEGIN 
INSERT INTO EMPLOYEE_LOG(EMPID,ACTIONTYPE,OLDSALARY,NEWSALARY)
VALUES
(OLD.EMPID, 'UPDATE' ,OLD.SALARY,NEW.SALARY);
END//
DELIMITER ;


-- TEST 
UPDATE EMPLOYEE
SET SALARY=30000
WHERE EMPID=1;


-- BEFORE DELETE 
DELIMITER //
CREATE TRIGGER BEFORE_DELETE_EMP
BEFORE DELETE ON EMPLOYEE FOR EACH ROW 
BEGIN 
IF OLD.PENDINGINVOICE >0 THEN 
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT ='CANNOT DELETE EMPLOYEE IF PENDING INVOICE EXISTS';
END IF ;
END//
DELIMITER ;

-- AFTER DELETE
DELIMITER //
CREATE TRIGGER AFTER_DELETE_EMP
AFTER DELETE ON EMPLOYEE FOR EACH ROW 
BEGIN 
INSERT INTO EMPLOYEE_LOG(EMPID,ACTIONTYPE,OLDSALARY)
VALUES
(OLD.EMPID,'DELETED',OLD.SALARY);
END//
DELIMITER ;


SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE WHERE EMPID=1;
