CREATE DATABASE SETOPERATIONS;
USE SETOPERATIONS;

CREATE TABLE DEPTA(
EMPID INT PRIMARY KEY ,
FNAME VARCHAR (50)
);

CREATE TABLE DEPTB(
EMPID INT PRIMARY KEY ,
FNAME VARCHAR (50)
);


INSERT INTO DEPTA VALUES
(1,'JHON'),(2,'JAMES'),(3,'BOB');

INSERT INTO DEPTB VALUES 
(3,'BOB'),(4,'MARK'),(5,'MARY');

SELECT  EMPID,FNAME FROM DEPTA 
UNION 
SELECT EMPID , FNAME FROM DEPTB;

SELECT  EMPID,FNAME FROM DEPTA 
UNION ALL
SELECT EMPID , FNAME FROM DEPTB;



-- SUBQUERY 
CREATE DATABASE SUBQUERY;
USE SUBQUERY;

CREATE TABLE EMPLOYEES(
EMPID INT PRIMARY KEY ,
ENAME VARCHAR(50),
DEPT VARCHAR (50),
SALARY int);


INSERT INTO EMPLOYEES VALUES 
(1,'A','HR',50000),
(2,'B','IT',55000),
(3,'C','FIANCE',50000),
(4,'D','IT',60000),
(5,'E','FINANCE',70000);
-- SCALAR SUBQUARY 
-- FIND EMPLOYE WITH HIIGHEST SALARY 
SELECT * FROM EMPLOYEES;

SELECT ENAME ,SALARY FROM EMPLOYEES 
WHERE SALARY =(SELECT MAX(SALARY) FROM EMPLOYEES );

-- MULTIPLE SUBQUARY 
-- FIND EMPLOYEE WHO WORK IN THE SAME  DEPT AS E 
SELECT ENAME ,DEPT FROM EMPLOYEES 
WHERE DEPT IN (
SELECT DEPT FROM EMPLOYEES 
WHERE ENAME ='E'
);



-- CORRELATED SUBQUERY 
SELECT ENAME ,DEPT,SALARY 
FROM EMPLOYEES E 
WHERE SALARY >(
SELECT AVG(SALARY)
FROM EMPLOYEES 
WHERE DEPT =E.DEPT
);





-- DERIVED TABLE 
-- CAL AVG SAL BY DEPT ,THEN GET DEPT WITH AVG SAL>55000
SELECT DT.DEPT ,DT.AVGSALARY
 FROM (
SELECT DEPT ,AVG(SALARY) AS AVGSALARY
FROM EMPLOYEES 
GROUP BY DEPT) AS DT 
WHERE DT.AVGSALARY >50000 ;


-- CTE 
-- CREATE CTE NAMED DEPTAVG TO CAL AVG SALARY PER DEPARTMENT 

WITH DEPTAVG AS(
SELECT DEPT ,AVG(SALARY) AS AVGSALARY
FROM EMPLOYEES 
GROUP BY DEPT
)
SELECT * FROM DEPTAVG 
WHERE AVGSALARY>60000;


 
 -- views 
 CREATE VIEW HIGHSALARYEMPLOYEES AS 
 SELECT * FROM EMPLOYEES 
 WHERE SALARY>60000;
 
 INSERT INTO EMPLOYEES VALUES
 (6,'ARUN','MARKETING',80000);
 
 
 -- DROP VIEW VIEWNAME;
 
 
