CREATE DATABASE StudentDB;
USE StudentDB;

-- TASK CONSTRAINTS AND DATA INTEGRITY
CREATE TABLE STUDENTSTBL(
STUDENTID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
STUDENTNAME VARCHAR(50) NOT NULL,
AGE INT CHECK(AGE>=18),
EMAIL VARCHAR(50) NOT NULL UNIQUE,
COURSE VARCHAR(20) DEFAULT "GENERAL",
MARKS INT CHECK(MARKS BETWEEN 0 AND 100));


INSERT INTO STUDENTSTBL(STUDENTNAME,AGE,EMAIL,COURSE,MARKS) VALUES
("PRASAD",26,"kagithala@gmail.com","BSC",100),
("VINOD",27,"vinnu@gmail.com","BZC",65),
("RAM",28,"ram@gmail.com","AQUA",69);
SELECT * FROM STUDENTSTBL;

-- TASK OPERATORS & FILTERING 
SELECT * FROM STUDENTSTBL 
WHERE MARKS >60 AND AGE<25;

SELECT * FROM STUDENTSTBL 
WHERE NOT COURSE="GENERAL";

SELECT * FROM STUDENTSTBL 
WHERE MARKS BETWEEN 50 AND 80;

SELECT * FROM STUDENTSTBL 
WHERE STUDENTNAME LIKE "R%";

SELECT * FROM STUDENTSTBL
WHERE EMAIL LIKE "%gmail%";


-- CLAUSES & DATA ANALYSIS 
SELECT * FROM STUDENTSTBL ORDER BY MARKS DESC;

SELECT * FROM STUDENTSTBL LIMIT 2;

SELECT DISTINCT COURSE FROM STUDENTSTBL;

SELECT COURSE,COUNT(COURSE) AS COUNTCOURSE
FROM STUDENTSTBL
GROUP BY COURSE 
HAVING COUNT(COURSE)=2;

