CREATE DATABASE IRISDB;
USE IRISDB;

CREATE TABLE IRIS(
SEPALLENGTH FLOAT NOT NULL,
SEPALWIDTH FLOAT NOT NULL ,
PETALLENGTH FLOAT NOT NULL,
PETALWIDTH FLOAT NOT NULL,
SPECIES VARCHAR(50) NOT NULL
);

SELECT * FROM IRIS;

-- VIEW  FIRST 10 ROWS FROM IRIS DATA SET 
SELECT * FROM IRIS LIMIT 10;

-- ALL UNIQUE RECORDS 
SELECT DISTINCT SPECIES FROM IRIS ;

-- COUNT HOW MANY RECORDS TO EACH SPECIES 
SELECT SPECIES ,COUNT(*) AS COUNT 
FROM IRIS 
GROUP BY SPECIES; 

-- SHOW TOP 5 ROWS WITH LARGEST SPECIAL LENGTH 
SELECT * FROM IRIS 
ORDER BY SEPALLENGTH DESC 
LIMIT 5;

 