CREATE DATABASE EMPLOY;
USE EMPLOY;

CREATE TABLE EMPLOYEES(
EMPLOYEEID INT,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
EMAIL VARCHAR(50),
PHONENUMBER VARCHAR(20) NOT NULL ,
HIRE_DATE DATE,
JOBTITLE VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY INT CHECK (SALARY>0),
STATUS_ VARCHAR(20) DEFAULT "WORKING",
UNIQUE(PHONENUMBER),
UNIQUE(EMAIL),
PRIMARY KEY(PHONENUMBER,DEPARTMENT)
);


INSERT INTO EMPLOYEES VALUES
(1,'JHON','DEEP','jhon@gmail.com','1234567891','2023-12-1','DATA ANALYST','IT',50000,"WORKING"),
(2,'BOB','MARLEY','bob@gmail.com','1234567899','2023-10-11','DATA ANALYST','IT',55000,"NOT WORKING"),
(3,'ROCK','POOL','rock@gmail.com','1234567888','2024-12-31','DATA SCIENTIST','IT',70000,"WORKING"),
(4,'PUSPHA','RAJ','puspha@gmail.com','1234567892','2025-05-04','HUNAM RESOURCE','HR',60000,"WORKING"),
(5,'DISCO','RAJ','disco@gmail.com','1234567897','2024-11-26','ASSOCIATE HR','HR',65000,"WORKING"),
(6,'ARJUN','VEER','arjun@gmail.com','1234567893','2022-08-22','EXCUTIVE','SALES',78000,"WORKING"),
(7,'RAM','DEER','ram@gmail.com','1234567890','2025-10-07','MANAGER','SALES',90000,"WORKING"),
(8,'ROCKY','BHAAI','rocky@gmail.com','1234567896','2021-12-1','GM','SALES',100000,"NOT WORKING");

SELECT * FROM EMPLOYEES;

-- AGGREGRATION FUNCTIONS 
SELECT COUNT(DEPARTMENT) AS COUNTOFEMPLOYEES FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT MAX(SALARY)AS MAXSALARY FROM EMPLOYEES;
SELECT MIN(SALARY) AS MINSALARY FROM EMPLOYEES;

SELECT AVG(SALARY) AS AVGSALARY,
SUM(SALARY) AS TOTALSALARY FROM EMPLOYEES
WHERE DEPARTMENT ='IT';

SELECT DEPARTMENT,SUM(SALARY)AS HEIGHTESTSALARY FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING HEIGHTESTSALARY>100000;

SELECT DEPARTMENT ,AVG(SALARY) AS AVSAL FROM EMPLOYEES
GROUP BY DEPARTMENT 
ORDER BY AVSAL DESC
LIMIT 1;

SELECT DEPARTMENT ,SUM(SALARY) AS TOTALSAL FROM EMPLOYEES
GROUP BY DEPARTMENT ;

SELECT DEPARTMENT,AVG(SALARY) AS AVGSA FROM EMPLOYEES
GROUP BY DEPARTMENT 
HAVING AVGSA >60000;




-- STRING FUNCTIONS 
SELECT CONCAT(FIRSTNAME, " ", LASTNAME)AS FULLNAME FROM EMPLOYEES; 

SELECT UPPER( CONCAT(FIRSTNAME, " ", LASTNAME))AS EMPLOYENAMES,
LOWER(DEPARTMENT) AS DEPARTMENT FROM EMPLOYEES;

SELECT CONCAT(FIRSTNAME ,LASTNAME)AS FULLNAME,CHAR_LENGTH(CONCAT(FIRSTNAME,LASTNAME))AS TOTALLENGTH FROM EMPLOYEES;

SELECT SUBSTR(DEPARTMENT,1,3) AS SHORTFORM FROM  EMPLOYEES;

SELECT REPLACE(DEPARTMENT,'SALES','ACCOUNTS') AS UPDATED FROM EMPLOYEES;





-- DATE AND TIME 

SELECT YEAR(HIRE_DATE) AS DATEOFHIRE,
MONTH(HIRE_DATE) AS MONTHOFHIRE,
DAY(HIRE_DATE)AS DAYOFHIRE FROM EMPLOYEES;

SELECT DATEDIFF(NOW(),HIRE_DATE ) AS NOOFDAYS FROM EMPLOYEES;

SELECT ADDDATE(HIRE_DATE ,INTERVAL 3 MONTH) AS UPDATED FROM EMPLOYEES;

SELECT SYSDATE()





-- CASE STATEMENT 

SELECT HIRE_DATE,
CASE 
WHEN YEAR(HIRE_DATE)<2020 THEN "EXPRIENCED"
WHEN YEAR(HIRE_DATE) BETWEEN 2020 AND 2022 THEN "MID-LEVEL"
WHEN YEAR(HIRE_DATE)>2022 THEN  "FRESHER"
END AS EXPRIENCELEVEL  FROM EMPLOYEES;

SELECT SALARY,
CASE 
WHEN SALARY<30000 THEN 'LOW'
WHEN SALARY <70000 THEN 'MEDIUM'
ELSE 'HIGH'
END AS SALARYLEVEL FROM EMPLOYEES;







-- ORDER OF EXCUTION 
SELECT DEPARTMENT ,COUNT(*) AS EX
FROM EMPLOYEES 
WHERE HIRE_DATE>'2022-01-01'
GROUP BY DEPARTMENT 
HAVING COUNT(*)>2
ORDER BY EX DESC
LIMIT 2 ;

